build_from:
  amd64: "ghcr.io/home-assistant/amd64-base-python:3.11-alpine3.18"
  aarch64: "ghcr.io/home-assistant/aarch64-base-python:3.11-alpine3.18"
  armv7: "ghcr.io/home-assistant/armv7-base-python:3.11-alpine3.18"
args:
  PYTHON_VERSION: "3.11" 