name: Device MQTT Bridge (PDU & Shelly)
version: "1.4.0"
slug: device_mqtt_bridge
description: "MQTT bridge for PDUs and Shelly devices with visual discovery"
arch:
  - amd64
  - aarch64
  - armv7
startup: application
boot: auto
init: false
host_network: true
webui: http://[HOST]:[PORT:8099]
ports:
  8099/tcp: 8099
ports_description:
  8099/tcp: "Visual device discovery interface"
options:
  mqtt_host: "localhost"
  mqtt_port: 1883
  mqtt_user: ""
  mqtt_password: ""
  mqtt_topic: "pdu"
  auto_discovery: true
  discovery_network: "192.168.1"
  discovery_range_start: 1
  discovery_range_end: 254
  device_list: []
schema:
  mqtt_host: str
  mqtt_port: int
  mqtt_user: str?
  mqtt_password: str?
  mqtt_topic: str
  auto_discovery: bool
  discovery_network: str
  discovery_range_start: int
  discovery_range_end: int
  device_list:
    - name: str
      host: str
      type: str
      username: str?
      password: str?