name: LogiLink & Intellinet PDU MQTT Bridge
version: "1.2-beta"
slug: pdu_mqtt
description: "MQTT bridge for multiple Logilink PDU8P01 and Intellinet 163682 (8x IEC-C13 smart PDU) via MQTT - BETA VERSION"
arch:
  - amd64
  - aarch64
  - armv7
startup: application
boot: auto
host_network: true
ingress: false
ingress_port: 0
panel_icon: mdi:power-plug
homeassistant_api: false
hassio_api: false
hassio_role: default
map:
  - config:rw
options:
  mqtt_host: "localhost"
  mqtt_port: 1883
  mqtt_user: "mqttuser"
  mqtt_password: "mqttpass"
  mqtt_topic: "pdu"
  auto_discovery: false
  discovery_network: "192.168.1"
  pdu_list:
    - name: "rack_01"
      host: "192.168.1.215"
      username: "admin"
      password: "admin"
  log_level: "INFO"
schema:
  mqtt_host: str
  mqtt_port: int(1, 65535)
  mqtt_user: str
  mqtt_password: str
  mqtt_topic: str
  auto_discovery: bool
  discovery_network: str
  log_level: list(DEBUG|INFO|WARNING|ERROR)
  pdu_list:
    - name: str
      host: str
      username: str
      password: str