name: "PDU MQTT Bridge"
description: "Professional PDU control and monitoring for Home Assistant - Supports LogiLink, Intellinet, and compatible smart PDUs"
version: "2.0.0"
slug: "pdu_mqtt"
arch:
  - amd64
  - aarch64
  - armv7
startup: application
boot: auto
host_network: true
ingress: false
ingress_port: 0
panel_icon: mdi:power-plug
homeassistant_api: false
hassio_api: false
hassio_role: default
map:
  - config:rw
options:
  # MQTT Configuration
  mqtt:
    host: "localhost"
    port: 1883
    username: ""
    password: ""
    topic_prefix: "pdu"
    discovery_prefix: "homeassistant"
    retain: true
  
  # PDU Configuration
  pdus:
    - name: "rack_01"
      host: "192.168.1.112"
      username: "admin"
      password: "admin"
      model: "auto"
      scan_interval: 30
  
  # Discovery Settings
  discovery:
    enabled: false
    network: "192.168.1"
    scan_interval: 300
    credentials:
      - username: "admin"
        password: "admin"
      - username: "admin"
        password: "password"
      - username: "root"
        password: "admin"
  
  # Advanced Settings
  advanced:
    log_level: "INFO"
    health_check: true
    parallel_requests: 5
    timeout: 10
    retry_attempts: 3

schema:
  mqtt:
    host: str
    port: int(1, 65535)
    username: str
    password: str
    topic_prefix: str
    discovery_prefix: str
    retain: bool
  
  pdus:
    - name: str
      host: str
      username: str
      password: str
      model: list(auto|logilink|intellinet|custom)
      scan_interval: int(10, 300)
  
  discovery:
    enabled: bool
    network: str
    scan_interval: int(60, 3600)
    credentials:
      - username: str
        password: str
  
  advanced:
    log_level: list(DEBUG|INFO|WARNING|ERROR)
    health_check: bool
    parallel_requests: int(1, 10)
    timeout: int(5, 30)
    retry_attempts: int(1, 5)