name: LogiLink & Intellinet PDU MQTT Bridge
version: "1.3.2"
slug: pdu_mqtt
description: "MQTT bridge for multiple Logilink PDU8P01 and Intellinet 163682 (8x IEC-C13 smart PDU) via MQTT"
arch:
  - amd64
  - aarch64
  - armv7
startup: application
boot: auto
init: false
host_network: true
options:
  mqtt_host: "localhost"
  mqtt_port: 1883
  mqtt_user: ""
  mqtt_password: ""
  mqtt_topic: "pdu"
  pdu_list:
    - name: rack_01
      host: "192.168.1.215"
      username: "admin"
      password: "admin"
schema:
  mqtt_host: str
  mqtt_port: int
  mqtt_user: str?
  mqtt_password: str?
  mqtt_topic: str
  pdu_list:
    - name: str
      host: str
      username: str
      password: str