---
name: "LogiLink PDU MQTT Bridge"
description: "Simple MQTT bridge for LogiLink PDU8P01 smart PDU"
version: "1.2.1"
slug: "pdu_mqtt"
arch:
  - amd64
  - aarch64
  - armv7
startup: application
boot: auto
host_network: true
ingress: false
ingress_port: 0
panel_icon: mdi:power-plug
homeassistant_api: false
hassio_api: false
hassio_role: default
map:
  - config:rw
options:
  mqtt_host: "localhost"
  mqtt_port: 1883
  mqtt_user: ""
  mqtt_password: ""
  pdu_list:
    - name: "rack_01"
      host: "192.168.1.215"
      username: "admin"
      password: "admin"
schema:
  mqtt_host: str
  mqtt_port: int(1, 65535)
  mqtt_user: str
  mqtt_password: str
  pdu_list:
    - name: str
      host: str
      username: str
      password: str