name: Intellinet PDU MQTT Bridge
version: "1.1"
slug: pdu_mqtt
description: "MQTT bridge for multiple Intellinet 163682 PDUs using longmover API"
arch:
  - amd64
  - aarch64
  - armv7
startup: application
boot: auto
host_network: true
options:
  mqtt_host: "localhost"
  mqtt_port: 1883
  mqtt_user: "mqttuser"
  mqtt_password: "mqttpass"
  mqtt_topic: "pdu"
  pdu_list:
    - name: rack_01
      host: "192.168.1.112"
      username: "admin"
      password: "admin"
schema:
  mqtt_host: str
  mqtt_port: int
  mqtt_user: str
  mqtt_password: str
  mqtt_topic: str
  pdu_list:
    - name: str
      host: str
      username: str
      password: str