# Home Assistant Configuration Example
# Add this to your configuration.yaml

# MQTT Configuration (required)
mqtt:
  broker: localhost
  port: 1883
  # username: mqttuser  # if needed
  # password: mqttpass  # if needed

# MQTT Switch Configuration (optional - auto-discovery should work)
switch:
  - platform: mqtt
    name: "PDU Outlet 1"
    command_topic: "pdu/outlet_1/set"
    state_topic: "pdu/outlet_1/state"
    availability_topic: "pdu/outlet_1/available"
    payload_on: "ON"
    payload_off: "OFF"
    state_on: "ON"
    state_off: "OFF"
    optimistic: false
    retain: true

  - platform: mqtt
    name: "PDU Outlet 8"
    command_topic: "pdu/outlet_8/set"
    state_topic: "pdu/outlet_8/state"
    availability_topic: "pdu/outlet_8/available"
    payload_on: "ON"
    payload_off: "OFF"
    state_on: "ON"
    state_off: "OFF"
    optimistic: false
    retain: true

# MQTT Sensor Configuration (optional - auto-discovery should work)
sensor:
  - platform: mqtt
    name: "PDU Outlet 1 Power"
    state_topic: "pdu/outlet_1/power"
    unit_of_measurement: "W"
    device_class: power
    availability_topic: "pdu/outlet_1/available"

  - platform: mqtt
    name: "PDU Outlet 8 Power"
    state_topic: "pdu/outlet_8/power"
    unit_of_measurement: "W"
    device_class: power
    availability_topic: "pdu/outlet_8/available" 